# Site settings
title: Stephanos Solutions
header-img: img/home-bg.png
email: stephanos@goldmail.etsu.edu
copyright_name: dkStephanos
description: > # this means to ignore newlines until "baseurl:"
  Web Development: A Journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  dkStephanos
learn_profile: dkStephanos
email_username: stephanos@goldmail.etsu.edu

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
